### ISSUE TITLE
Unhandled error when reaching limit of alerts per account

### ISSUE THREAD

**Issue by adamniedzielski** [pivotus/galerts#1]
There is a limit of 1000 alerts per account.
If this limit is reached the code will break with following exception:
`undefined method `[]' for nil:NilClass` in `galerts-1.0.4/lib/galerts/manager.rb:139:in `create'`

In this case `response_body` is equal to `[nil,4,nil,""]`. I believe this should be handled in the same way as `ALERT_SOMETHING_WENT_WRONG` or `ALERT_NOT_EXIST`. This will definitely simplify debugging this issue.

What's your opinion on this? Will you welcome a pull request?

**Comment by ecylmz** [comment]
I missed this situation.

> What's your opinion on this? Will you welcome a pull request?

Of course, i would be grateful.
