### ISSUE TITLE
Undefined method 'tr' for nil:NilClass on create

### ISSUE THREAD

**Issue by jamintz** [pivotus/galerts#6]
manager = Galerts::Manager.new(UN,PW)
irb(main):055:0> new_alert = manager.create("my awesome keywords", {
irb(main):056:2\*   :frequency => Galerts::RT,
irb(main):057:2\*   :domain => 'es',
irb(main):058:2\*   :language => "es",
irb(main):059:2\*   :how_many => Galerts::ALL_RESULTS,
irb(main):060:2\*   :delivery => Galerts::RSS
irb(main):061:2>   })
NoMethodError: undefined method `tr' for nil:NilClass
    from vendor/bundle/gems/galerts-1.1.2/lib/galerts/manager.rb:133:in`create'
    from (irb):55
    from vendor/bundle/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
    from vendor/bundle/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in`start'
    from vendor/bundle/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
    from vendor/bundle/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in`run_command!'
    from vendor/bundle/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in`require'
    from bin/rails:4:in `<main>'

**Comment by ecylmz** [comment]
Hi,

What is your ruby version?

**Comment by jamintz** [comment]
2.2.4p230

It was previously working but fired it up this morning and began having issues, might have changed something on my end but I can't track it down

**Comment by ecylmz** [comment]
``` ruby
    new_alert = manager.create("my awesome keywords", {                                                                                                                                                         
      :domain => 'es',                                                                                                                                                                     
      :language => 'es',                                                                                                                                                                       
      :how_many => Galerts::ALL_RESULTS,                                                                                                                                                       
      :frequency => Galerts::RT,                                                                                                                                                               
      :delivery => Galerts::RSS                                                                                                                                                                
    }) 
```

I can't reproduce this problem :( I tried to above example, it worked. Can you try different gmail address? Maybe Google giving errors for your account.

**Comment by jamintz** [comment]
...thank you, gmail had blocked my account

**Comment by kevinhq** [comment]
Gmail sign in did work, but still got same error.
I am on ruby 1.9.3
