### ISSUE TITLE
Sign in not working?

### ISSUE THREAD

**Issue by jamintz** [pivotus/galerts#7]
I've been using this gem successfully for a bit, it suddenly seems to be broken for sign-in. If I do x=Galerts::Manager.new(UN,PW) with my correct info, I get x.alerts to be [] when there should be alerts. This is the same thing that happens if I do a completely made up UN, PW, so seems like it's not logging me in correctly

**Comment by jamintz** [comment]
I'm using ruby 2.2.3p173, last time this issue popped up (https://github.com/pivotus/galerts/issues/6) it was because google had blocked my account, this doesn't seem to be the case now.

@ecylmz could you confirm this is working with your google account?

**Comment by ecylmz** [comment]
I have the same problem. As soon as we try to solve this problem.

**Comment by ecylmz** [comment]
fixed with this commit: https://github.com/pivotus/galerts/commit/64693c80ca30237324243801555e16a10965841f

**Comment by jamintz** [comment]
Thanks, works for me now
